Revert "Upgrade google-cloud pubsub"
The API wasn't upgraded completely, and the cloud functions throw errors
like this:

        TypeError: pull() takes from 1 to 2 positional arguments but 3
        positional arguments (and 1 keyword-only argument) were given

The API usage needs to be reviewed carefully and all changed calls
updated and tested.

This reverts commit ef70ebdd8f963271626f6b7ea9ae4c3c4f2262ea.